services:
  app:
    container_name: appname_php
    build:
        context: ./docker/php
        dockerfile: Dockerfile
        args:
            UID: ${UID}
            GID: ${GID}
    volumes:
      - ./src:/var/www
    ports:
      - "9000:9000"
    networks:
      - appname_internal_network
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    container_name: appname_nginx
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - appname_internal_network
    depends_on:
      - app
    
  mysql:
    image: mysql:latest
    container_name: appname_mysql
    volumes:
      - appname_mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - appname_internal_network
    environment:
      MYSQL_ROOT_PASSWORD: secret

networks:
  appname_internal_network:

volumes:
  appname_mysql_data: